name: Deploy Frontend

on:
  push:
    branches:
      - main
    paths:
      - 'zatudan-frontend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy Frontend
    steps:
      - uses: actions/checkout@v3

      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash

      - name: Set up Bun path
        run: echo "$HOME/.bun/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: bun install
        working-directory: ./zatudan-frontend

      - name: Set Environment Variables
        run: echo "REACT_APP_CF_BACKEND_API_URL=${{ secrets.REACT_APP_CF_BACKEND_API_URL }}" >> $GITHUB_ENV

      - name: Build the project
        run: bun run build
        working-directory: ./zatudan-frontend

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          projectName: "zatudan-frontend"
          directory: "./build"
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          workingDirectory: './zatudan-frontend'

